# Generated by Django 2.2.10 on 2020-04-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('slides', '0003_kipyacard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='slides_customcontent', serialize=False, to='cms.CMSPlugin')),
                ('custome_content_html', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
